Repository NebulousCloud/helix-plugins, pull requests merged in 2019-12, with the labels that each got.

#13 Upload the Player Flags plugin
  sh_playerflags.lua
Labels: plugin-submission

#14 Add Combine Voices and Local Event.
  combinevoices.lua
  localevent.lua
Labels: plugin-submission

#12 Class Whitelists
  classwhitelists/README
  classwhitelists/sh_plugin.lua
Labels: plugin-submission

#11 added betterdesc and weight
  betterdesc.lua
  weight/LICENCE
  weight/sh_meta.lua
  weight/sh_plugin.lua
  weight/sv_plugin.lua
Labels: missing-license, plugin-submission

#10 Added Overwatch Rank Manager plugin.
  rankmanager.lua
Labels: plugin-submission

#20 Initial pull-request of bodygroup manager
  bodygroupmanager/LICENSE
  bodygroupmanager/README.md
  bodygroupmanager/cl_hooks.lua
  bodygroupmanager/derma/cl_viewer.lua
  bodygroupmanager/sh_plugin.lua
  bodygroupmanager/sv_hooks.lua
Labels: plugin-submission

#22 Upload the perma classes plugin
  perma_class.lua
Labels: plugin-submission

#23 Fixed airwatch lines
  combinevoices.lua
Labels: plugin-update

#24 Fixed bodygroups not sticking after charswap.
  bodygroupmanager/sv_hooks.lua
Labels: plugin-update
